import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/haeder/haeder";
import Stars from "./components/stars/stars";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className={"notice"}>
          <Stars />
          {children}
        </div>
      </body>
    </html>
  );
}
